-- 1. Buat tipe ENUM jika belum ada (Taruh di luar atau di awal transaksi)
CREATE TYPE public.user_role AS ENUM ('user', 'admin', 'root'); 
-- *Catatan: Sesuaikan isi enum ('user', 'admin', 'root') dengan kebutuhan aplikasi dashlo kamu.

-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;

CREATE TABLE IF NOT EXISTS public.app_users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    username character varying(64) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role public.user_role NOT NULL DEFAULT 'user'::public.user_role,
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    last_login timestamp with time zone,
    allowed_areas text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    CONSTRAINT app_users_pkey PRIMARY KEY (id),
    CONSTRAINT app_users_email_key UNIQUE (email),
    CONSTRAINT app_users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.area_overrides
(
    city_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    area_slug character varying(100) COLLATE pg_catalog."default" NOT NULL,
    area_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    agent_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    regional character varying(100) COLLATE pg_catalog."default",
    area_id serial NOT NULL,
    CONSTRAINT area_overrides_pkey PRIMARY KEY (area_id),
    CONSTRAINT uq_area_slug UNIQUE (area_slug),
    CONSTRAINT uq_city_name UNIQUE (city_name)
);

COMMENT ON TABLE public.area_overrides
    IS 'Tabel pemetaan nama kota/kabupaten ke area ID tertentu untuk override data sales';

COMMENT ON COLUMN public.area_overrides.city_name
    IS 'Nama kota/kabupaten dari kolom AREA/KOTA di excel';

COMMENT ON COLUMN public.area_overrides.area_slug
    IS 'Slug dari nama agen (contoh: cv_arta_setia)';

COMMENT ON COLUMN public.area_overrides.area_name
    IS 'Nama agen/perwakilan dari kolom NAMA AGEN di excel';

COMMENT ON COLUMN public.area_overrides.agent_type
    IS 'Jenis: agen atau perwakilan (dari kolom JENIS di excel)';

COMMENT ON COLUMN public.area_overrides.regional
    IS 'Nama regional yang terkait dengan area';

CREATE TABLE IF NOT EXISTS public.login_logs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    ip_address text COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    success boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT login_logs_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.login_logs
    IS 'Riwayat percobaan login (berhasil & gagal)';

COMMENT ON COLUMN public.login_logs.user_id
    IS 'Referensi ke app_users. cascade delete.';

COMMENT ON COLUMN public.login_logs.ip_address
    IS 'Alamat IP dari mana percobaan login dilakukan (dari x-forwarded-for atau remoteAddress).';

COMMENT ON COLUMN public.login_logs.user_agent
    IS 'User-Agent header dari browser/client';

COMMENT ON COLUMN public.login_logs.success
    IS 'true = login berhasil, false = password salah / akun nonaktif';

CREATE TABLE IF NOT EXISTS public.product_price_histories
(
    history_id serial NOT NULL,
    product_price_id integer NOT NULL,
    product_id integer NOT NULL,
    area_id integer NOT NULL,
    dbp numeric(14, 2),
    wbp numeric(14, 2),
    rbp numeric(14, 2),
    cbp numeric(14, 2),
    pita_cukai numeric(14, 2),
    hje numeric(14, 2),
    tarif numeric(14, 2),
    hpp numeric(14, 2),
    action character varying(10) COLLATE pg_catalog."default" NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    changed_by character varying(100) COLLATE pg_catalog."default" DEFAULT CURRENT_USER,
    CONSTRAINT product_price_histories_pkey PRIMARY KEY (history_id)
);

CREATE TABLE IF NOT EXISTS public.product_prices
(
    id serial NOT NULL,
    product_id integer NOT NULL,
    area_id integer NOT NULL,
    dbp numeric(14, 2) NOT NULL DEFAULT 0,
    wbp numeric(14, 2) NOT NULL DEFAULT 0,
    rbp numeric(14, 2) NOT NULL DEFAULT 0,
    cbp numeric(14, 2) NOT NULL DEFAULT 0,
    pita_cukai numeric(14, 2) NOT NULL DEFAULT 0,
    hje numeric(14, 2) NOT NULL DEFAULT 0,
    tarif numeric(14, 2) NOT NULL DEFAULT 0,
    hpp numeric(14, 2) NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT product_prices_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_price UNIQUE (product_id, area_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category character varying(10) COLLATE pg_catalog."default" NOT NULL,
    factory character varying(100) COLLATE pg_catalog."default" NOT NULL,
    stick_per_pack integer NOT NULL,
    pack_per_slop integer NOT NULL DEFAULT 10,
    slop_per_bal integer NOT NULL,
    bal_per_dos integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_name_key UNIQUE (name)
);

ALTER TABLE IF EXISTS public.app_users
    ADD CONSTRAINT app_users_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.login_logs
    ADD CONSTRAINT login_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.product_price_histories
    ADD CONSTRAINT pph_changed_by_fkey FOREIGN KEY (changed_by)
    REFERENCES public.app_users (username) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.product_prices
    ADD CONSTRAINT product_prices_area_id_fkey FOREIGN KEY (area_id)
    REFERENCES public.area_overrides (area_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pp_area_id
    ON public.product_prices(area_id);

ALTER TABLE IF EXISTS public.product_prices
    ADD CONSTRAINT product_prices_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pp_product_id
    ON public.product_prices(product_id);

COMMIT;